dataset: cremi
mode: multi
device: 0
batch_size: 8
# dist_sf_l1_gamma: 1.0
multi:
  conn_nums: [ 8, 24 ]
  label_modes: [ binary, dist, dist_inverted ]
  dist_aux_losses: [ smooth_l1, cl_dice ]
  folds: 1
