dataset: [ cremi ]
mode: multi
device: 1
batch_size: 8
multi:
  epochs: 500
  folds: 1
  conn_nums: [ 8 ]
  conn_layouts: [ out8 ]
  label_modes: [ binary, dist, dist_inverted ]
  dist_aux_losses: [ smooth_l1 ]
