dataset: [ cremi ]
mode: multi
device: 1
dist_sf_l1_gamma: 1.0
multi:
  skip_completed: true
  epochs: 500
  folds: 1
  experiments_only: true
  experiments:
    - conn_num: 8
      conn_layout: standard8
      label_mode: binary
      dist_aux_loss: smooth_l1
      conn_fusion: dg_direct
      fusion_loss_profile: A
      use_seg_aux: true
      seg_aux_weight: 0.5
