dataset: [ chase ]
mode: multi
device: 3
dist_sf_l1_gamma: 1.0
multi:
  epochs: 500
  folds: 1
  experiments_only: true
  fusion_lambda_inner: 0.2
  fusion_lambda_outer: 0.05
  fusion_lambda_fused: 0.3
  experiments:
    - dataset: chase
      conn_num: 8
      conn_layout: standard8
      label_mode: dist
      dist_aux_loss: gjml_sf_l1
      conn_fusion: scaled_sum
      fusion_loss_profile: A
      fusion_residual_scale: 0.5
    - dataset: chase
      conn_num: 8
      conn_layout: standard8
      label_mode: dist_inverted
      dist_aux_loss: smooth_l1
      conn_fusion: scaled_sum
      fusion_loss_profile: A
      fusion_residual_scale: 0.1
    - dataset: chase
      conn_num: 8
      conn_layout: standard8
      label_mode: dist_inverted
      dist_aux_loss: smooth_l1
      conn_fusion: scaled_sum
      fusion_loss_profile: A
      fusion_residual_scale: 0.2
    - dataset: chase
      conn_num: 8
      conn_layout: standard8
      label_mode: dist_inverted
      dist_aux_loss: smooth_l1
      conn_fusion: scaled_sum
      fusion_loss_profile: A
      fusion_residual_scale: 0.3
    - dataset: chase
      conn_num: 8
      conn_layout: standard8
      label_mode: dist_inverted
      dist_aux_loss: smooth_l1
      conn_fusion: scaled_sum
      fusion_loss_profile: A
      fusion_residual_scale: 0.5
    - dataset: chase
      conn_num: 8
      conn_layout: standard8
      label_mode: dist_inverted
      dist_aux_loss: gjml_sf_l1
      conn_fusion: scaled_sum
      fusion_loss_profile: A
      fusion_residual_scale: 0.1
    - dataset: chase
      conn_num: 8
      conn_layout: standard8
      label_mode: dist_inverted
      dist_aux_loss: gjml_sf_l1
      conn_fusion: scaled_sum
      fusion_loss_profile: A
      fusion_residual_scale: 0.2
    - dataset: chase
      conn_num: 8
      conn_layout: standard8
      label_mode: dist_inverted
      dist_aux_loss: gjml_sf_l1
      conn_fusion: scaled_sum
      fusion_loss_profile: A
      fusion_residual_scale: 0.3
    - dataset: chase
      conn_num: 8
      conn_layout: standard8
      label_mode: dist_inverted
      dist_aux_loss: gjml_sf_l1
      conn_fusion: scaled_sum
      fusion_loss_profile: A
      fusion_residual_scale: 0.5
