dataset: [ octa500 ]
mode: multi
device: 1
dist_sf_l1_gamma: 1.0
multi:
  epochs: 500
  folds: 1
  octa_variants: [ 3M, 6M ]
  conn_nums: [ 8 ]
  label_modes: [ binary, dist, dist_inverted ]
  dist_aux_losses: [ smooth_l1 ]
